# pymc/datapack.py
import os
import json
from datetime import datetime
from .core import MCFunction

# --------------------------
# ✅ DATAPACK WRITER (auto-generate valid MC datapacks)
# --------------------------
class Datapack:
    """
    Writes a complete, valid Minecraft datapack from PyMC MCFunction objects.
    Auto-creates folder structure, pack.mcmeta, load tags, and function files.
    Ready to drop into Minecraft's datapacks folder!
    """
    def __init__(self, name: str, mc_version: str = "1.20"):
        self.name = name.strip().replace(" ", "_")
        self.mc_version = mc_version
        self.root = os.path.join("generated_datapacks", self.name)
        self.functions_dir = os.path.join(self.root, "functions")
        self.tags_dir = os.path.join(self.root, "tags", "functions")

    def _create_folders(self) -> None:
        """Auto-create all required folders"""
        os.makedirs(self.functions_dir, exist_ok=True)
        os.makedirs(self.tags_dir, exist_ok=True)

    def write_pack_meta(self) -> None:
        """Write the required pack.mcmeta file (MC needs this to recognize the datapack)"""
        self._create_folders()
        pack_meta = {
            "pack": {
                "pack_format": 15,  # 1.20 = 15, adjust for your MC version
                "description": f"PyMC Generated Datapack | {datetime.now().strftime('%Y-%m-%d')}"
            }
        }
        with open(os.path.join(self.root, "pack.mcmeta"), "w") as f:
            json.dump(pack_meta, f, indent=2)

    def write_function(self, func: MCFunction) -> None:
        """Write an MCFunction object to a .mcfunction file (correct namespace folder)"""
        self._create_folders()
        func_dir = os.path.join(self.functions_dir, func.namespace)
        os.makedirs(func_dir, exist_ok=True)
        func_path = os.path.join(func_dir, f"{func.name}.mcfunction")

        # Add auto-comment header
        header = [
            "# Auto-generated by PyMC (Python JMC Clone)",
            f"# Function: {func.full_name()}",
            f"# Generated: {datetime.now().strftime('%H:%M:%S')}",
            "# -------------------------"
        ]
        content = "\n".join(header + func.commands)

        with open(func_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✅ Wrote function: {func_path}")

    def write_load_tag(self, load_func: MCFunction) -> None:
        """Write load.json tag (runs a function when the datapack loads)"""
        self._create_folders()
        load_tag = {"values": [load_func.full_name()]}
        with open(os.path.join(self.tags_dir, "load.json"), "w") as f:
            json.dump(load_tag, f, indent=2)
        print(f"✅ Load tag written (runs on datapack load)")